name: Expressiones
run-name: Corriendo expresiones
on:
  workflow_dispatch:
    inputs:
      edad:
        description: "Edad"
        required: true
        type: number
      nombre:
        description: "Tu nombre"
        required: true
        default: "Daniel"
        type: string

jobs:
  mayor:
    if: ${{ github.event.inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: correr script
        run: echo ${{ github.event.inputs.nombre }} es mayor de edad

  menor:
    if: ${{ github.event.inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: correr script
        run: echo ${{ github.event.inputs.nombre }} es menor de edad
