name: Expression
on:
    worlflow_dispatch:
      inputs:
        edad:
          description: "Edad"
          required: true
          type: integer
        nombre:
          description: "Tu nombre"
          required: true
          default: "Daniel"
          type: String
        
jobs:
    mayor:
      if: ${{ inputs.edad >= 18 }}
      runs-on: ubuntu-latest
      steps:
          - name : correr script
              run: echo ${{ inputs.nombre }} es mayor de edad
    menor:
      if: ${{ inputs.edad <= 18 }}
      runs-on: ubuntu-latest
      steps:
          - name : correr script
              run: echo ${{ inputs.nombre }} es menor de edad
